name: Deploy to Heroku

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행
    paths:
      - 'backend/**' 

  workflow_dispatch:  # 수동으로 실행 가능
    inputs:
      environment:
        description: 'Choose the environment to deploy'
        required: true
        default: 'production'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.12 

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY | heroku auth:token
        git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:refs/heads/main --force

