name: Deploy to Heroku

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.12 

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Authenticate with Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Deploy to Heroku
      run: |
        cd backend
        git init
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
        git add .
        git commit -m "Deploying to Heroku"
        git push heroku main --force
